### ISSUE TITLE
Dataset Architecture

### ISSUE THREAD

**Issue by ZirshaRiaz** [Dohppak/Music-Emotion-Recognition-Classification#1]
Hi! 
I am thankful to you for sharing the implementation. I am trying to implement it and enhance this. But first step is that I need dataset. Can you please share dataset and guide me about the hierarchy that how to use it. Thank you so much.
Waiting for your kind response.

**Comment by seungheondoh** [comment]
I also sent a mail to the original author of the mail, but it was not shared due to copyright issues ... so I built a dataset with a data crawl.  I attach the original author's repository

https://github.com/deezer/deezer_mood_detection_dataset

**Comment by ZirshaRiaz** [comment]
Ok thank you
